<?php
/*
    * Ongage Magento Plug-in
    * Version 1.0
    * Released March, 2014
    * Credits: Jaldip Upadhyay, Krunal Patel, Pratik Patel, Dharmesh Vasani
    * Terms of Service: http://www.ongage.com/legal-terms/terms-of-service
    * Copyright (C) Ongage
*/
?>
<table>
    <tr>
        <td>
            <button style="" onclick="javascript:window.open('<?php echo $this->getButtonUrl()?>', 'apiwizard'); return false;" class="scalable" type="button" id="none">
                <span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span>
            </button>
        </td>
    </tr>
</table>